name: backend

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          cd backend && docker build --no-cache \
          --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
          -t jithingeorge10/stock-api .

      - name: Push the Docker image
        run: docker push jithingeorge10/stock-api
